### Master Seminar Physical Geography 2026
## Elevational Temperature Gradient and seasonal variability in Greenland 2010-2026
#### Lea Pietrek & Miriam Erdler
---
#### 💡 Aim of the Project: characterize how elevational temperature gradients across Greenland have evolved using PROMICE Station Pairs

---
---

## Settings

In [5]:
# install necessary libraries
!pip install pandas numpy matplotlib seaborn scipy pymannkendall jupyter

Requirement already satisfied: pandas in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (3.0.2)
Requirement already satisfied: numpy in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (2.4.4)
Requirement already satisfied: matplotlib in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (3.10.9)
Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting scipy
  Downloading scipy-1.17.1-cp311-cp311-win_amd64.whl.metadata (60 kB)
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.0 kB ? eta -:--:--
     ------------ ------------------------- 20.5/61.0 kB 131.3 kB/s eta 0:00:01
     ------------------- ------------------ 30.7/61.0 kB 145.2 kB/s eta 0:00:01
     ------------------- ------------------ 30.7/61.0 kB 145.2 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.0 kB 187.0 kB/s eta 0:00:01
     -------------------------------------- 61.0/61.0 kB 190.6 kB/s eta 0:00:00
Collecting pymannkendall
  Downloading pymannkendall-1.4.3-py3-none-any.whl.metadata (14 kB)
Collecting jupyter
  Using cached jupyter-1.1.1-py2.py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (from matplotlib) (3.3.2)
Collecting notebook (from jupyter)
  Using cached notebook-7.5.5-py3-none-any.whl.metadata (10 kB)
Collecting jupyter-console (from jupyter)
  Using cached jupyter_console-6.6.3-py3-none-any.whl.metadata (5.8 kB)
Collecting nbconvert (from jupyter)
  Using cached nbconvert-7.17.1-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: ipykernel in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (from jupyter) (7.2.0)
Collecting ipywidgets (from jupyter)
  Using cached ipywidgets-8.1.8-py3-none-any.whl.metadata (2.4 kB)
Collecting jupyterlab (from jupyter)
  Using cached jupyterlab-4.5.6-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: six>=1.5 in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: comm>=0.1.1 in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (from ipykernel->jupyter) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (from ipykernel->jupyter) (1.8.20)
Requirement already satisfied: ipython>=7.23.1 in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (from ipykernel->jupyter) (9.13.0)
Requirement already satisfied: jupyter-client>=8.8.0 in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (from ipykernel->jupyter) (8.8.0)
Requirement already satisfied: jupyter-core!=6.0.*,>=5.1 in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (from ipykernel->jupyter) (5.9.1)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (from ipykernel->jupyter) (0.2.1)
Requirement already satisfied: nest-asyncio>=1.4 in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (from ipykernel->jupyter) (1.6.0)
Requirement already satisfied: psutil>=5.7 in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (from ipykernel->jupyter) (7.2.2)
Requirement already satisfied: pyzmq>=25 in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (from ipykernel->jupyter) (27.1.0)
Requirement already satisfied: tornado>=6.4.1 in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (from ipykernel->jupyter) (6.5.5)
Requirement already satisfied: traitlets>=5.4.0 in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (from ipykernel->jupyter) (5.14.3)
Collecting widgetsnbextension~=4.0.14 (from ipywidgets->jupyter)
  Using cached widgetsnbextension-4.0.15-py3-none-any.whl.metadata (1.6 kB)
Collecting jupyterlab_widgets~=3.0.15 (from ipywidgets->jupyter)
  Using cached jupyterlab_widgets-3.0.16-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: prompt-toolkit>=3.0.30 in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (from jupyter-console->jupyter) (3.0.52)
Requirement already satisfied: pygments in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (from jupyter-console->jupyter) (2.20.0)
Collecting async-lru>=1.0.0 (from jupyterlab->jupyter)
  Using cached async_lru-2.3.0-py3-none-any.whl.metadata (7.6 kB)
Collecting httpx<1,>=0.25.0 (from jupyterlab->jupyter)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting jinja2>=3.0.3 (from jupyterlab->jupyter)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting jupyter-lsp>=2.0.0 (from jupyterlab->jupyter)
  Using cached jupyter_lsp-2.3.1-py3-none-any.whl.metadata (1.8 kB)
Collecting jupyter-server<3,>=2.4.0 (from jupyterlab->jupyter)
  Using cached jupyter_server-2.17.0-py3-none-any.whl.metadata (8.5 kB)
Collecting jupyterlab-server<3,>=2.28.0 (from jupyterlab->jupyter)
  Using cached jupyterlab_server-2.28.0-py3-none-any.whl.metadata (5.9 kB)
Collecting notebook-shim>=0.2 (from jupyterlab->jupyter)
  Using cached notebook_shim-0.2.4-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: setuptools>=41.1.0 in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (from jupyterlab->jupyter) (65.5.0)
Collecting beautifulsoup4 (from nbconvert->jupyter)
  Using cached beautifulsoup4-4.14.3-py3-none-any.whl.metadata (3.8 kB)
Collecting bleach!=5.0.0 (from bleach[css]!=5.0.0->nbconvert->jupyter)
  Using cached bleach-6.3.0-py3-none-any.whl.metadata (31 kB)
Collecting defusedxml (from nbconvert->jupyter)
  Using cached defusedxml-0.7.1-py2.py3-none-any.whl.metadata (32 kB)
Collecting jupyterlab-pygments (from nbconvert->jupyter)
  Using cached jupyterlab_pygments-0.3.0-py3-none-any.whl.metadata (4.4 kB)
Collecting markupsafe>=2.0 (from nbconvert->jupyter)
  Using cached markupsafe-3.0.3-cp311-cp311-win_amd64.whl.metadata (2.8 kB)
Collecting mistune<4,>=2.0.3 (from nbconvert->jupyter)
  Using cached mistune-3.2.0-py3-none-any.whl.metadata (1.9 kB)
Collecting nbclient>=0.5.0 (from nbconvert->jupyter)
  Using cached nbclient-0.10.4-py3-none-any.whl.metadata (8.3 kB)
Collecting nbformat>=5.7 (from nbconvert->jupyter)
  Using cached nbformat-5.10.4-py3-none-any.whl.metadata (3.6 kB)
Collecting pandocfilters>=1.4.1 (from nbconvert->jupyter)
  Using cached pandocfilters-1.5.1-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting webencodings (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert->jupyter)
  Using cached webencodings-0.5.1-py2.py3-none-any.whl.metadata (2.1 kB)
Collecting tinycss2<1.5,>=1.1.0 (from bleach[css]!=5.0.0->nbconvert->jupyter)
  Using cached tinycss2-1.4.0-py3-none-any.whl.metadata (3.0 kB)
Collecting anyio (from httpx<1,>=0.25.0->jupyterlab->jupyter)
  Using cached anyio-4.13.0-py3-none-any.whl.metadata (4.5 kB)
Requirement already satisfied: certifi in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (2026.4.22)
Collecting httpcore==1.* (from httpx<1,>=0.25.0->jupyterlab->jupyter)
  Using cached httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Collecting idna (from httpx<1,>=0.25.0->jupyterlab->jupyter)
  Using cached idna-3.13-py3-none-any.whl.metadata (8.0 kB)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab->jupyter)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Requirement already satisfied: colorama>=0.4.4 in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.4.6)
Requirement already satisfied: decorator>=5.1.0 in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.19.2)
Requirement already satisfied: stack_data>=0.6.0 in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.6.3)
Requirement already satisfied: typing_extensions>=4.6 in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (4.15.0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (from jupyter-core!=6.0.*,>=5.1->ipykernel->jupyter) (4.9.6)
Collecting argon2-cffi>=21.1 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached argon2_cffi-25.1.0-py3-none-any.whl.metadata (4.1 kB)
Collecting jupyter-events>=0.11.0 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached jupyter_events-0.12.1-py3-none-any.whl.metadata (5.8 kB)
Collecting jupyter-server-terminals>=0.4.4 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached jupyter_server_terminals-0.5.4-py3-none-any.whl.metadata (5.9 kB)
Collecting overrides>=5.0 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached overrides-7.7.0-py3-none-any.whl.metadata (5.8 kB)
Collecting prometheus-client>=0.9 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached prometheus_client-0.25.0-py3-none-any.whl.metadata (2.1 kB)
Collecting pywinpty>=2.0.1 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached pywinpty-3.0.3-cp311-cp311-win_amd64.whl.metadata (5.9 kB)
Collecting send2trash>=1.8.2 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached send2trash-2.1.0-py3-none-any.whl.metadata (4.1 kB)
Collecting terminado>=0.8.3 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached terminado-0.18.1-py3-none-any.whl.metadata (5.8 kB)
Collecting websocket-client>=1.7 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached websocket_client-1.9.0-py3-none-any.whl.metadata (8.3 kB)
Collecting babel>=2.10 (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Using cached babel-2.18.0-py3-none-any.whl.metadata (2.2 kB)
Collecting json5>=0.9.0 (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Using cached json5-0.14.0-py3-none-any.whl.metadata (36 kB)
Collecting jsonschema>=4.18.0 (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Using cached jsonschema-4.26.0-py3-none-any.whl.metadata (7.6 kB)
Collecting requests>=2.31 (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Using cached requests-2.33.1-py3-none-any.whl.metadata (4.8 kB)
Collecting fastjsonschema>=2.15 (from nbformat>=5.7->nbconvert->jupyter)
  Using cached fastjsonschema-2.21.2-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: wcwidth in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (from prompt-toolkit>=3.0.30->jupyter-console->jupyter) (0.6.0)
Collecting soupsieve>=1.6.1 (from beautifulsoup4->nbconvert->jupyter)
  Using cached soupsieve-2.8.3-py3-none-any.whl.metadata (4.6 kB)
Collecting argon2-cffi-bindings (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached argon2_cffi_bindings-25.1.0-cp39-abi3-win_amd64.whl.metadata (7.5 kB)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (from jedi>=0.18.2->ipython>=7.23.1->ipykernel->jupyter) (0.8.6)
Requirement already satisfied: attrs>=22.2.0 in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (26.1.0)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Using cached referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.25.0 (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Using cached rpds_py-0.30.0-cp311-cp311-win_amd64.whl.metadata (4.2 kB)
Collecting python-json-logger>=2.0.4 (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached python_json_logger-4.1.0-py3-none-any.whl.metadata (3.7 kB)
Collecting pyyaml>=5.3 (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached pyyaml-6.0.3-cp311-cp311-win_amd64.whl.metadata (2.4 kB)
Collecting rfc3339-validator (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached rfc3339_validator-0.1.4-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting rfc3986-validator>=0.1.1 (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached rfc3986_validator-0.1.1-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting charset_normalizer<4,>=2 (from requests>=2.31->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Using cached charset_normalizer-3.4.7-cp311-cp311-win_amd64.whl.metadata (41 kB)
Collecting urllib3<3,>=1.26 (from requests>=2.31->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Using cached urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: executing>=1.2.0 in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel->jupyter) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel->jupyter) (3.0.1)
Requirement already satisfied: pure-eval in c:\users\miria\documents\uni\4_semester\seminar_phy\.venv\lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel->jupyter) (0.2.3)
Collecting fqdn (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached fqdn-1.5.1-py3-none-any.whl.metadata (1.4 kB)
Collecting isoduration (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached isoduration-20.11.0-py3-none-any.whl.metadata (5.7 kB)
Collecting jsonpointer>1.13 (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached jsonpointer-3.1.1-py3-none-any.whl.metadata (2.4 kB)
Collecting rfc3987-syntax>=1.1.0 (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached rfc3987_syntax-1.1.0-py3-none-any.whl.metadata (7.7 kB)
Collecting uri-template (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached uri_template-1.3.0-py3-none-any.whl.metadata (8.8 kB)
Collecting webcolors>=24.6.0 (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached webcolors-25.10.0-py3-none-any.whl.metadata (2.2 kB)
Collecting cffi>=1.0.1 (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached cffi-2.0.0-cp311-cp311-win_amd64.whl.metadata (2.6 kB)
Collecting pycparser (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
Collecting lark>=1.2.2 (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached lark-1.3.1-py3-none-any.whl.metadata (1.8 kB)
Collecting arrow>=0.15.0 (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached arrow-1.4.0-py3-none-any.whl.metadata (7.7 kB)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading scipy-1.17.1-cp311-cp311-win_amd64.whl (36.6 MB)
   ---------------------------------------- 0.0/36.6 MB ? eta -:--:--
   ---------------------------------------- 0.1/36.6 MB 1.7 MB/s eta 0:00:23
   ---------------------------------------- 0.3/36.6 MB 3.4 MB/s eta 0:00:11
   ---------------------------------------- 0.4/36.6 MB 3.3 MB/s eta 0:00:12
    --------------------------------------- 0.5/36.6 MB 2.8 MB/s eta 0:00:13
   - -------------------------------------- 1.0/36.6 MB 4.4 MB/s eta 0:00:09
   - -------------------------------------- 1.3/36.6 MB 4.9 MB/s eta 0:00:08
   -- ------------------------------------- 1.9/36.6 MB 5.7 MB/s eta 0:00:07
   -- ------------------------------------- 2.2/36.6 MB 5.8 MB/s eta 0:00:06
   -- ------------------------------------- 2.5/36.6 MB 5.9 MB/s eta 0:00:06
   --- ------------------------------------ 2.8/36.6 MB 5.9 MB/s eta 0:00:06
   --- ------------------------------------ 3.2/36.6 MB 6.1 MB/s eta 0:00:06
   --- ------------------------------------ 3.5/36.6 MB 6.2 MB/s eta 0:00:06
   ---- ----------------------------------- 4.0/36.6 MB 6.5 MB/s eta 0:00:06
   ---- ----------------------------------- 4.4/36.6 MB 6.5 MB/s eta 0:00:05
   ----- ---------------------------------- 5.0/36.6 MB 6.8 MB/s eta 0:00:05
   ----- ---------------------------------- 5.3/36.6 MB 6.9 MB/s eta 0:00:05
   ----- ---------------------------------- 5.3/36.6 MB 6.9 MB/s eta 0:00:05
   ------ --------------------------------- 5.7/36.6 MB 6.5 MB/s eta 0:00:05
   ------ --------------------------------- 6.3/36.6 MB 6.7 MB/s eta 0:00:05
   ------ --------------------------------- 6.3/36.6 MB 6.8 MB/s eta 0:00:05
   ------ --------------------------------- 6.3/36.6 MB 6.8 MB/s eta 0:00:05
   ------- -------------------------------- 6.5/36.6 MB 6.2 MB/s eta 0:00:05
   ------- -------------------------------- 6.6/36.6 MB 6.2 MB/s eta 0:00:05
   ------- -------------------------------- 6.7/36.6 MB 5.8 MB/s eta 0:00:06
   ------- -------------------------------- 6.9/36.6 MB 5.8 MB/s eta 0:00:06
   -------- ------------------------------- 7.4/36.6 MB 5.9 MB/s eta 0:00:05
   -------- ------------------------------- 7.8/36.6 MB 6.1 MB/s eta 0:00:05

[notice] A new release of pip is available: 24.0 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
# import necessary libraries
import pandas as pd #reading and manipulating data
import numpy as np #numerical operations
from pathlib import Path #handling file paths

## Data Cleaning

##### Paths: This section defines all folder paths used in the workflow. Using relative paths instead of local machine paths ensures that the notebook can be executed on different computers without modifying the code.

In [17]:
# Define paths and constants

# project root = current folder
PROJECT_ROOT = Path.cwd()

# paths
RAW_DATA = PROJECT_ROOT / "Data" / "Data_RAW"

PROCESSED_DATA = PROJECT_ROOT / "Data" / "Data_Processed"

CLEAN_DATA = PROCESSED_DATA / "Cleaned_Stations"

# create output folder
CLEAN_DATA.mkdir(parents=True, exist_ok=True)

# test
print(RAW_DATA)

c:\Users\miria\Documents\UNI\4_Semester\SEMINAR_PHY\SE_402.212_GreenlandTemperature\Data\Data_RAW

In [23]:
# List all CSV files in the raw data directory
# The workflow is designed to automatically detect all PROMICE station files, 
# making it scalable and reducing the need for manual file selection.

csv_files = list(RAW_DATA.glob("*.csv"))

print(f"Found {len(csv_files)} CSV files")

for file in csv_files:
    print(file.name)

Found 18 CSV files
KAN_L_month.csv
KAN_U_month.csv
KPC_L_month.csv
KPC_U_month.csv
NUK_L_month.csv
NUK_U_month.csv
QAS_L_month.csv
QAS_U_month.csv
SCO_L_month.csv
SCO_U_month.csv
TAS_L_month.csv
TAS_U_month.csv
THU_L_month.csv
THU_U_month.csv
UPE_L_month.csv
UPE_U_month.csv
ZAC_L_month.csv
ZAC_U_month.csv

In [19]:
# Read a sample file to check the structure

sample_file = csv_files[0]

df = pd.read_csv(sample_file)

df.head()

,time,p_u,t_u,rh_u,rh_u_wrt_ice_or_water,qh_u,wspd_u,wdir_u,wspd_x_u,wspd_y_u,...,gps_alt,lat,lon,alt,batt_v,t_rad,t_i,rh_i_wrt_ice_or_water,wdir_i,wspd_y_i
0,2008-09-01,923.9882,-2.5934,79.9399,81.6629,2.8476,3.3134,133.9854,1.8320,-1.7682,...,676.17,67.097312,-49.931913,678.73,13.45,-2.0476,-2.5962,81.6650,134.9669,-1.7649
1,2008-10-01,924.2335,-8.8390,76.7142,81.4251,1.8167,4.5009,136.0388,2.4764,-2.5678,...,675.85,67.097292,-49.932110,678.70,13.25,-8.9245,-8.8353,82.3774,134.6686,-2.6032
2,2008-11-01,924.7323,-10.8112,81.3601,88.1435,1.6097,4.3467,133.9104,2.3021,-2.2162,...,674.28,67.097272,-49.932309,678.66,12.82,-11.2204,-10.8295,88.6081,131.1321,-2.2228
3,2008-12-01,916.8134,-15.4373,71.2094,78.6264,1.0833,5.7925,140.0709,3.3923,-4.0529,...,670.38,67.097251,-49.932509,678.63,12.55,-15.9078,-15.4285,83.5962,140.3030,-3.9943
4,2009-01-01,912.9546,-13.5028,62.6707,68.1504,1.1081,5.3631,129.9273,3.7522,-3.1404,...,678.00,67.097231,-49.932711,678.60,12.55,-14.0442,-13.4724,73.9714,124.2769,-3.1638

In [13]:
# Check column names
df.columns

Index(['time', 'p_u', 't_u', 'rh_u', 'rh_u_wrt_ice_or_water', 'qh_u', 'wspd_u',
       'wdir_u', 'wspd_x_u', 'wspd_y_u', 'dsr', 'dsr_cor', 'usr', 'usr_cor',
       'albedo', 'dlr', 'ulr', 'cc', 't_surf', 'dlhf_u', 'dshf_u', 'z_boom_u',
       'z_boom_cor_u', 'z_stake', 'z_stake_cor', 'z_pt', 'z_pt_cor',
       'z_surf_combined', 'z_ice_surf', 'snow_height', 'rainfall_u',
       'rainfall_cor_u', 't_i_1', 't_i_2', 't_i_3', 't_i_4', 't_i_5', 't_i_6',
       't_i_7', 't_i_8', 'd_t_i_1', 'd_t_i_2', 'd_t_i_3', 'd_t_i_4', 'd_t_i_5',
       'd_t_i_6', 'd_t_i_7', 'd_t_i_8', 't_i_10m', 'tilt_x', 'tilt_y', 'rot',
       'gps_lat', 'gps_lon', 'gps_alt', 'lat', 'lon', 'alt', 'batt_v', 't_rad',
       't_i', 'rh_i_wrt_ice_or_water', 'wdir_i', 'wspd_y_i'],
      dtype='str')

##### Extract Metadata from File Names:
PROMICE file names contain important metadata information.
Example:

`KAN_L_month.csv`

From this naming structure we extract:
- station ID (`KAN`)
- station level (`L` = lower station, `U` = upper station)
- temporal resolution (`month`)
  
This metadata will later help identify station pairs and distinguish between elevation levels.

In [ ]:
# Extract information from filename 
def extract_station_info(file_path):
    """
    Extract information from filename.

    Example:
    KAN_L_month.csv
    """

    parts = file_path.stem.split("_")

    station_id = parts[0]
    station_level = parts[1]
    temporal_resolution = parts[2]

    return station_id, station_level, temporal_resolution

##### Define Data Cleaning Function

This function performs the main preprocessing steps for each PROMICE file.

The cleaning workflow includes:

- reading the CSV file
- replacing invalid missing value codes (`-999`, `-9999`) with NaN
- selecting only relevant variables for the analysis
- adding metadata extracted from the filename
- converting timestamps into datetime format
- removing duplicate rows
- sorting observations chronologically

The raw data files remain unchanged throughout this process.

In [27]:
def clean_promice_file(file_path):

    # Extract station info from filename

    station_id, station_level, temporal_resolution = extract_station_info(file_path)

    # Read the CSV file

    df = pd.read_csv(file_path)

    # Replace -999 and -9999 with NaN

    df = df.replace([-999, -9999], np.nan)

    # Keep only relevant columns
    columns_to_keep = [
        "time",
        "gps_lat",
        "gps_lon",
        "gps_alt",
        "t_u",
        "t_l",
        "t_i",
        "rh_u",
        "rh_l"
    ]

    existing_columns = [
        col for col in columns_to_keep
        if col in df.columns
    ]

    df = df[existing_columns]

    # Time Conversion - convert to datetime if "time" column exists

    if "time" in df.columns:
        df["time"] = pd.to_datetime(df["time"])

    # Cleaning - remove duplicates, sort by time, reset index
    df = df.drop_duplicates()

    if "time" in df.columns:
        df = df.sort_values("time")

    df = df.reset_index(drop=True)

    return df

##### Clean all PROMICE Files
This section applies the cleaning function to all PROMICE files automatically.

Each cleaned dataset is saved separately in the `Cleaned_Stations` folder.

The original naming structure is preserved to maintain information about:
- station ID
- elevation level
- temporal resolution

In [28]:
# Process all files and save cleaned versions
for file in csv_files:

    cleaned_df = clean_promice_file(file)

    station_id, station_level, temporal_resolution = extract_station_info(file)

    output_filename = (
        f"{station_id}_{station_level}_{temporal_resolution}_clean.csv"
    )

    output_path = CLEAN_DATA / output_filename

    cleaned_df.to_csv(output_path, index=False)

print("All files cleaned successfully.")

All files cleaned successfully.

#### Data Quality Check

In [29]:
# Find all cleaned files
cleaned_files = list(CLEAN_DATA.glob("*.csv"))

# Create dictionary for datasets
station_data = {}

# Load all cleaned datasets
for file in cleaned_files:
    
    df = pd.read_csv(file)
    
    # Store using filename as key
    station_data[file.stem] = df

# Show loaded datasets
print(f"Loaded {len(station_data)} cleaned datasets")

print("\nDatasets:")
for key in station_data.keys():
    print(key)

Loaded 18 cleaned datasets

Datasets:
KAN_L_month_clean
KAN_U_month_clean
KPC_L_month_clean
KPC_U_month_clean
NUK_L_month_clean
NUK_U_month_clean
QAS_L_month_clean
QAS_U_month_clean
SCO_L_month_clean
SCO_U_month_clean
TAS_L_month_clean
TAS_U_month_clean
THU_L_month_clean
THU_U_month_clean
UPE_L_month_clean
UPE_U_month_clean
ZAC_L_month_clean
ZAC_U_month_clean

Checking missing values

In [32]:
missing_by_variable = {}

for name, df in station_data.items():
    
    missing_by_variable[name] = df.isna().mean() * 100  # percent missing

missing_df = pd.DataFrame(missing_by_variable)

missing_df

# the table shows the % of missing values for each variable in each station dataset.
# This helps identify which variables have the most missing data across stations, guiding further analysis and cleaning steps.

,KAN_L_month_clean,KAN_U_month_clean,KPC_L_month_clean,KPC_U_month_clean,NUK_L_month_clean,NUK_U_month_clean,QAS_L_month_clean,QAS_U_month_clean,SCO_L_month_clean,SCO_U_month_clean,TAS_L_month_clean,TAS_U_month_clean,THU_L_month_clean,THU_U_month_clean,UPE_L_month_clean,UPE_U_month_clean,ZAC_L_month_clean,ZAC_U_month_clean
gps_alt,17.452830,33.658537,30.046948,16.431925,18.721461,17.777778,15.555556,29.577465,46.009390,79.439252,50.446429,60.000000,49.171271,54.143646,11.0,20.5,7.798165,60.280374
gps_lat,17.452830,33.658537,30.046948,16.431925,18.721461,17.777778,16.444444,30.046948,46.009390,79.439252,50.446429,60.000000,49.171271,54.143646,11.0,20.0,7.798165,60.280374
gps_lon,17.452830,35.121951,30.046948,16.431925,19.634703,17.777778,16.444444,30.046948,46.009390,79.439252,50.446429,60.000000,49.171271,54.143646,11.0,20.0,7.798165,60.280374
rh_l,NaN,95.609756,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
rh_u,5.188679,3.414634,23.004695,11.737089,21.004566,12.000000,1.777778,16.901408,1.408451,9.813084,24.107143,18.888889,20.441989,3.867403,7.5,10.0,5.504587,22.429907
t_i,6.603774,25.365854,36.619718,38.967136,31.963470,20.888889,18.666667,29.107981,28.638498,39.719626,68.303571,31.111111,38.121547,22.099448,17.0,47.0,83.944954,90.186916
t_l,NaN,89.268293,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
t_u,0.471698,5.853659,25.821596,14.553991,15.981735,17.333333,3.555556,15.492958,6.572770,14.953271,30.357143,25.555556,22.099448,7.734807,9.5,14.0,11.009174,25.233645
time,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000